/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package improjecr;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;



/**
 *
 * @author gtger
 */
public class Orderform extends javax.swing.JFrame {

    /**
     * Creates new form Orderform
     */
    public Orderform() {
        initComponents();
        dt(); //date
        time(); //time
    }
    
        Connection con1,con2;
        PreparedStatement insert,insert2;
   
 public void dt(){
     
     Date d = new Date();
     SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
     String dd =sdf.format(d);
     ldate.setText(dd);
 }
 Timer t ;
 SimpleDateFormat st;
 public void time(){
     
     
     
     t=new Timer(0, new ActionListener() {
         @Override
         public void actionPerformed(ActionEvent e) {
             //throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
         Date dt =new Date();
         st = new SimpleDateFormat("hh:mm:ss a");
         
         String tt= st.format(dt);
         ltime.setText(tt);
        
         }
     });
     
    t.start();
 }
 
    DefaultTableModel model;
    String prodcode, prodname;
    String size, flavor, add_ons, sugar_lvl;  
    double price;
    
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtname = new javax.swing.JTextField();
        txtaddress = new javax.swing.JTextField();
        txtcontact = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        pnmilktea = new javax.swing.JRadioButton();
        pnfruittea = new javax.swing.JRadioButton();
        pnsmoothie = new javax.swing.JRadioButton();
        jLabel15 = new javax.swing.JLabel();
        frmilktea = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        frfruittea = new javax.swing.JComboBox<>();
        frsmoothie = new javax.swing.JComboBox<>();
        small = new javax.swing.JRadioButton();
        medium = new javax.swing.JRadioButton();
        large = new javax.swing.JRadioButton();
        addtocart = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        addons = new javax.swing.JComboBox<>();
        jLabel18 = new javax.swing.JLabel();
        sugarlvl = new javax.swing.JComboBox<>();
        jLabel19 = new javax.swing.JLabel();
        txtqty = new javax.swing.JSpinner();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tcart = new javax.swing.JTable();
        placeorder = new javax.swing.JButton();
        bremove = new javax.swing.JButton();
        ldate = new javax.swing.JLabel();
        ltime = new javax.swing.JLabel();
        total = new javax.swing.JTextField();
        custid = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        sfee = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        vcode = new javax.swing.JTextField();
        enter = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();
        discount = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        gamount = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        modep = new javax.swing.JComboBox<>();
        orderid = new javax.swing.JTextField();
        backmn = new javax.swing.JButton();
        jLabel38 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel87 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(223, 252, 252));

        jLabel1.setBackground(new java.awt.Color(255, 204, 204));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 40)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(238, 67, 16));
        jLabel1.setText("                           ORDER FORM/CART");
        jLabel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 102, 102), 2, true));
        jLabel1.setOpaque(true);

        jPanel2.setBackground(new java.awt.Color(255, 255, 204));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 102, 102), 3, true));

        jLabel4.setBackground(new java.awt.Color(255, 204, 204));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(238, 67, 16));
        jLabel4.setText("                                               CUSTOMER'S INFORMATION");
        jLabel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 102, 102), 2, true));
        jLabel4.setOpaque(true);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(92, 22, 22));
        jLabel5.setText("CUSTOMER ID:");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(92, 22, 22));
        jLabel7.setText("NAME:");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(92, 22, 22));
        jLabel8.setText("ADDRESS:");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(92, 22, 22));
        jLabel9.setText("CONTACT NUMBER:");

        txtname.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnameActionPerformed(evt);
            }
        });

        txtaddress.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtaddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtaddressActionPerformed(evt);
            }
        });

        txtcontact.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtcontact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcontactActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(92, 22, 22));
        jLabel6.setText("DATE:");

        jLabel3.setBackground(new java.awt.Color(255, 204, 204));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(238, 67, 16));
        jLabel3.setText("                                                      ORDER INFORMATION");
        jLabel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 102, 102), 2, true));
        jLabel3.setOpaque(true);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(92, 22, 22));
        jLabel2.setText("ORDER ID:");

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(92, 22, 22));
        jLabel10.setText("PRODUCT NAME:");

        pnmilktea.setBackground(new java.awt.Color(255, 255, 255));
        pnmilktea.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        pnmilktea.setForeground(new java.awt.Color(92, 22, 22));
        pnmilktea.setText("Milktea");

        pnfruittea.setBackground(new java.awt.Color(255, 255, 255));
        pnfruittea.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        pnfruittea.setForeground(new java.awt.Color(92, 22, 22));
        pnfruittea.setText("Fruit tea");
        pnfruittea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pnfruitteaActionPerformed(evt);
            }
        });

        pnsmoothie.setBackground(new java.awt.Color(255, 255, 255));
        pnsmoothie.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        pnsmoothie.setForeground(new java.awt.Color(92, 22, 22));
        pnsmoothie.setText("Smoothie");
        pnsmoothie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pnsmoothieActionPerformed(evt);
            }
        });

        jLabel15.setBackground(new java.awt.Color(255, 255, 255));
        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(92, 22, 22));
        jLabel15.setText("FLAVOR:");

        frmilktea.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        frmilktea.setForeground(new java.awt.Color(92, 22, 22));
        frmilktea.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-----", "Matcha green tea", "Jolly strawberry", "Happy Oreo", "Classic Milktea", "Cookies & gream" }));
        frmilktea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                frmilkteaActionPerformed(evt);
            }
        });

        jLabel16.setBackground(new java.awt.Color(255, 255, 255));
        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(92, 22, 22));
        jLabel16.setText("SIZE:");

        frfruittea.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        frfruittea.setForeground(new java.awt.Color(92, 22, 22));
        frfruittea.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-----", "Lemon", "Orange", "Strawberry", "Mango", "Apple" }));
        frfruittea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                frfruitteaActionPerformed(evt);
            }
        });

        frsmoothie.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        frsmoothie.setForeground(new java.awt.Color(92, 22, 22));
        frsmoothie.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-----", "Avocado", "Tropical Mango", "Watermelon", "Strawberry almond", "Four seasons" }));
        frsmoothie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                frsmoothieActionPerformed(evt);
            }
        });

        small.setBackground(new java.awt.Color(255, 255, 255));
        small.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        small.setForeground(new java.awt.Color(92, 22, 22));
        small.setText("Small");
        small.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smallActionPerformed(evt);
            }
        });

        medium.setBackground(new java.awt.Color(255, 255, 255));
        medium.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        medium.setForeground(new java.awt.Color(92, 22, 22));
        medium.setText("Medium");
        medium.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mediumActionPerformed(evt);
            }
        });

        large.setBackground(new java.awt.Color(255, 255, 255));
        large.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        large.setForeground(new java.awt.Color(92, 22, 22));
        large.setText("Large");
        large.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                largeActionPerformed(evt);
            }
        });

        addtocart.setBackground(new java.awt.Color(0, 102, 102));
        addtocart.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        addtocart.setForeground(new java.awt.Color(255, 255, 204));
        addtocart.setText("ADD TO CART");
        addtocart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addtocartActionPerformed(evt);
            }
        });

        jLabel17.setBackground(new java.awt.Color(255, 255, 255));
        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(92, 22, 22));
        jLabel17.setText("SUGAR LEVEL:");

        addons.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        addons.setForeground(new java.awt.Color(92, 22, 22));
        addons.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Pearls", "Toppings", "Crystals", "Jelly", "Pudding", " " }));
        addons.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addonsActionPerformed(evt);
            }
        });

        jLabel18.setBackground(new java.awt.Color(255, 255, 255));
        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(92, 22, 22));
        jLabel18.setText("ADD ONS(+10PHP)");

        sugarlvl.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        sugarlvl.setForeground(new java.awt.Color(92, 22, 22));
        sugarlvl.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "10%", "25%", "50%", "75%", "100%" }));
        sugarlvl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sugarlvlActionPerformed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(92, 22, 22));
        jLabel19.setText("QUANTITY:");

        jLabel11.setBackground(new java.awt.Color(255, 204, 204));
        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(238, 67, 16));
        jLabel11.setText("                                                                      CART");
        jLabel11.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 102, 102), 2, true));
        jLabel11.setOpaque(true);

        tcart.setBackground(new java.awt.Color(204, 255, 255));
        tcart.setForeground(new java.awt.Color(102, 51, 0));
        tcart.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product Code", "Product Name", "Flavor", "Size", "Add-ons", "Sugar level", "Unit price", "quantity", "Total "
            }
        ));
        jScrollPane2.setViewportView(tcart);

        placeorder.setBackground(new java.awt.Color(0, 102, 102));
        placeorder.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        placeorder.setForeground(new java.awt.Color(255, 255, 204));
        placeorder.setText("PLACE ORDER");
        placeorder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                placeorderActionPerformed(evt);
            }
        });

        bremove.setBackground(new java.awt.Color(255, 153, 51));
        bremove.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bremove.setForeground(new java.awt.Color(255, 255, 204));
        bremove.setText("REMOVE");
        bremove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bremoveActionPerformed(evt);
            }
        });

        ldate.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ldate.setForeground(new java.awt.Color(92, 22, 22));

        ltime.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ltime.setForeground(new java.awt.Color(92, 22, 22));

        total.setEditable(false);
        total.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        total.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalActionPerformed(evt);
            }
        });

        jLabel31.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        jLabel31.setText("Shipping fee:");

        jLabel30.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        jLabel30.setText("Total Amount:");

        sfee.setFont(new java.awt.Font("Bookman Old Style", 1, 18)); // NOI18N
        sfee.setForeground(new java.awt.Color(255, 51, 51));

        jLabel13.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        jLabel13.setText("Voucher Code:");

        vcode.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        vcode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vcodeActionPerformed(evt);
            }
        });

        enter.setBackground(new java.awt.Color(255, 0, 102));
        enter.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        enter.setForeground(new java.awt.Color(255, 255, 204));
        enter.setText("ENTER");
        enter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterActionPerformed(evt);
            }
        });

        jLabel25.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        jLabel25.setText("Discount:");

        discount.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        discount.setForeground(new java.awt.Color(255, 51, 51));

        jLabel27.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        jLabel27.setText("Grand Total Amount:");

        jLabel26.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        jLabel26.setText("-------------------------------------------------------------------------");

        gamount.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        gamount.setForeground(new java.awt.Color(255, 51, 51));

        jLabel28.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        jLabel28.setText("-------------------------------------------------------------------------");

        jLabel29.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        jLabel29.setText("Mode of Payment:");

        modep.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        modep.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cash", "Gcash", "Bank Transfer" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(9, 9, 9)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(pnsmoothie, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(pnfruittea, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(pnmilktea, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addComponent(jLabel10))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(frmilktea, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(frfruittea, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(frsmoothie, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(57, 57, 57))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(63, 63, 63)
                                        .addComponent(jLabel15)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(small, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(medium, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(large, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(61, 61, 61))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addGap(80, 80, 80)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(sugarlvl, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(jLabel17))
                            .addComponent(addons, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(59, 59, 59)
                                .addComponent(addtocart))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(91, 91, 91)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel19)
                                    .addComponent(txtqty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(426, 426, 426)
                                .addComponent(bremove, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(89, 89, 89)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(custid, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 0, Short.MAX_VALUE))
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                                                .addComponent(txtname, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel9)
                                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGap(53, 53, 53)
                                                .addComponent(ldate, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(ltime, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(txtcontact, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtaddress)))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(55, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(42, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 797, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(total, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel31)
                                .addGap(36, 36, 36)
                                .addComponent(sfee, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel27)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(gamount, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel29)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(modep, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(vcode, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(enter))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel25)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(discount, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(222, 222, 222))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(placeorder)
                        .addGap(352, 352, 352))))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(191, 191, 191)
                    .addComponent(orderid, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(591, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(ldate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(custid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(ltime, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtname, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtcontact, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtaddress, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtqty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sugarlvl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addtocart, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(98, 98, 98))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(pnfruittea)
                                    .addComponent(frfruittea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(medium))
                                .addGap(39, 39, 39))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(pnmilktea)
                                    .addComponent(frmilktea, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(small, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(addons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(106, 106, 106)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pnsmoothie)
                            .addComponent(frsmoothie, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(large))
                        .addGap(68, 68, 68)))
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bremove, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel30)
                        .addComponent(total, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(59, 59, 59)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel31)
                        .addGap(23, 23, 23))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(sfee, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(vcode, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(enter, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jLabel25))
                    .addComponent(discount, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel26)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel27))
                    .addComponent(gamount, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel28)
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(modep, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel29, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(55, 55, 55)
                .addComponent(placeorder, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(101, 101, 101))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(355, 355, 355)
                    .addComponent(orderid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(1230, Short.MAX_VALUE)))
        );

        backmn.setBackground(new java.awt.Color(255, 102, 102));
        backmn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        backmn.setForeground(new java.awt.Color(255, 255, 204));
        backmn.setText("BACK TO MAIN MENU");
        backmn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backmnActionPerformed(evt);
            }
        });

        jLabel38.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 70)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(117, 178, 79));
        jLabel38.setText("MA");

        jLabel50.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 70)); // NOI18N
        jLabel50.setForeground(new java.awt.Color(255, 0, 102));
        jLabel50.setText("JO");

        jLabel51.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 70)); // NOI18N
        jLabel51.setForeground(new java.awt.Color(255, 153, 51));
        jLabel51.setText("HA");

        jLabel87.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel87.setForeground(new java.awt.Color(153, 0, 51));
        jLabel87.setText("  ----- Milktea Shop ------");

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/improjecr/Illustration14-ImResizer (5).png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel38)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel50)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel51))
                            .addComponent(jLabel87, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel12)
                        .addGap(231, 231, 231))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(backmn)
                        .addGap(355, 355, 355))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel38)
                            .addComponent(jLabel50)
                            .addComponent(jLabel51))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel87)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel12)
                        .addGap(28, 28, 28)))
                .addComponent(jLabel1)
                .addGap(47, 47, 47)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(backmn, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(84, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 962, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 562, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backmnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backmnActionPerformed
        // TODO add your handling code here:
        mainwindow jf2 = new mainwindow();
        jf2.show(); //display orderform here
        dispose(); // close current frame after opening Orderform
    }//GEN-LAST:event_backmnActionPerformed

    private void enterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterActionPerformed
        // TODO add your handling code here:
        double disc=0.00,gamt=0.00, sf=50.00;
        if ("MAJOHA80".equals(vcode.getText())){
            disc = 80;
            discount.setText(Double.toString(disc));
        }
        else if ("DRJILL50".equals(vcode.getText())){
            disc = 50;
            discount.setText(Double.toString(disc));
        }
        else if ("OHAYO30".equals(vcode.getText())){
            disc = 30;
            discount.setText(Double.toString(disc));
        }
        else {
            discount.setText("INVALID CODE");
        }
        gamt = Double.parseDouble(total.getText())- disc + sf;
        gamount.setText(Double.toString(gamt));
    }//GEN-LAST:event_enterActionPerformed

    private void vcodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vcodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vcodeActionPerformed

    private void totalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalActionPerformed

    private void bremoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bremoveActionPerformed
        // TODO add your handling code here:
        model.removeRow(tcart.getSelectedRow());

        double sum = 0,sf=50,gamt = 0;
            for(int a=0; a<tcart.getRowCount(); a++)
            {
                sum = sum + Double.parseDouble(tcart.getValueAt(a, 8).toString());

            }
            total.setText(Double.toString(sum));                                
            sfee.setText(Double.toString(sf));
            gamt = sf + sum;
            gamount.setText(Double.toString(gamt));
            
        
    }//GEN-LAST:event_bremoveActionPerformed

    private void placeorderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_placeorderActionPerformed
        // TODO add your handling code here:
        //display orderform here

        String order_ID =orderid.getText();
        String date = ldate.getText();
        String t_amount= total.getText();
        String sf= sfee.getText();
        String vrcode=vcode.getText();
        String gt_amount= gamount.getText();
        String mop= modep.getSelectedItem().toString();
        String cust_ID = custid.getText();
        String cust_name = txtname.getText();
        String cust_add = txtaddress.getText();
        String contact_no = txtcontact.getText();
        String prod_code, prod_name, flavor, sizes, unit_price,sugar_level,add_ons,qty,total;

        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            con1 =DriverManager.getConnection("jdbc:mysql://localhost:3306/majohadatabase","root","");
            insert =con1.prepareStatement("insert into order(order_ID,date,cust_ID,t_amount,sfee,vcode,gt_amount,mop)values(?,?,?,?,?,?,?,?)");
            
            insert.setString(1,order_ID);
            insert.setString(2,date);
            insert.setString(3,cust_ID);
            insert.setString(4,t_amount);
            insert.setString(5,sf);
            insert.setString(6,vrcode);
            insert.setString(7,gt_amount);
            insert.setString(8,mop);
            insert.executeUpdate();
            
            insert =con1.prepareStatement("insert into ordered_product(prode_code,sugar_level,add_ons,qty,total)values(?,?,?,?,?)");
            for(int i=0; i<tcart.getRowCount();i++){
                    prod_code = tcart.getValueAt(i,0).toString();
                    sugar_level = tcart.getValueAt(i,5).toString();
                    add_ons = tcart.getValueAt(i,4).toString();
                    qty = tcart.getValueAt(i,7).toString();
                    total = tcart.getValueAt(i,8).toString();
            insert.setString(2,prod_code);
            insert.setString(3,sugar_level);
            insert.setString(4,add_ons);
            insert.setString(5,qty);
            insert.setString(6,total);
            insert.executeUpdate();
            }
            
            insert =con1.prepareStatement("insert into customer(cust_ID,cust_name,cust_add,contact_no)values(?,?,?,?)");
            insert.setString(1,cust_ID);
            insert.setString(2,cust_name);
            insert.setString(3,cust_add);
            insert.setString(4,contact_no);
            insert.executeUpdate();
            
            for(int i=0; i<tcart.getRowCount();i++){
                    prod_code = tcart.getValueAt(i,0).toString();
                    prod_name = tcart.getValueAt(i,1).toString();
                    flavor = tcart.getValueAt(i,2).toString();
                    sizes = tcart.getValueAt(i,3).toString();
                    unit_price = tcart.getValueAt(i,6).toString();

                    insert =con1.prepareStatement("insert into product(prod_code,prod_name,flavor,sizes,unit_price)values(?,?,?,?,?)");

                    insert.setString(1,prod_code);
                    insert.setString(2,prod_name);
                    insert.setString(3,flavor);
                    insert.setString(4,sizes);
                    insert.setString(5,unit_price);
                    insert.executeUpdate();

                }
            JOptionPane.showMessageDialog(this,"Order has been placed");

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Orderform.class.getName()).log(Level.SEVERE, null, ex);
        }
        catch (SQLException ex) {
            Logger.getLogger(Orderform.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_placeorderActionPerformed

    private void sugarlvlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sugarlvlActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sugarlvlActionPerformed

    private void addonsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addonsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addonsActionPerformed

    private void addtocartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addtocartActionPerformed
        // TODO add your handling code here:

        if(pnmilktea.isSelected() == true && small.isSelected() == true
            && frmilktea.getSelectedIndex()== 1)
        {
            prodcode = "MT123S";
            prodname = "Milktea";
            flavor = frmilktea.getSelectedItem().toString();
            add_ons = addons.getSelectedItem().toString();
            sugar_lvl=sugarlvl.getSelectedItem().toString();

            size = "small";
            price = 100.00;

        }
        else if(pnmilktea.isSelected() == true && medium.isSelected() == true
            && frmilktea.getSelectedIndex()== 1)
        {
            prodcode = "MT123M";
            prodname = "Milktea";
            flavor = frmilktea.getSelectedItem().toString();
            add_ons = addons.getSelectedItem().toString();
            sugar_lvl=sugarlvl.getSelectedItem().toString();
            size = "Medium";
            price = 150.00;
        }
        else if(pnmilktea.isSelected() == true && large.isSelected() == true
            && frmilktea.getSelectedIndex()== 1)
        {
            prodcode = "MT123L";
            prodname = "Milktea";
            flavor = frmilktea.getSelectedItem().toString();
            add_ons = addons.getSelectedItem().toString();
            sugar_lvl=sugarlvl.getSelectedItem().toString();
            size = "Large";
            price = 200.00;
        }
        else if(pnmilktea.isSelected() == true && small.isSelected() == true
            && frmilktea.getSelectedIndex()== 2)
        {
            prodcode = "MT124S";
            prodname = "Milktea";
            flavor = frmilktea.getSelectedItem().toString();
            add_ons = addons.getSelectedItem().toString();
            sugar_lvl=sugarlvl.getSelectedItem().toString();
            size = "small";
            price = 100.00;

        }
        else if(pnmilktea.isSelected() == true && medium.isSelected() == true
            && frmilktea.getSelectedIndex()== 2)
        {
            prodcode = "MT124M";
            prodname = "Milktea";
            flavor = frmilktea.getSelectedItem().toString();
            add_ons = addons.getSelectedItem().toString();
            sugar_lvl=sugarlvl.getSelectedItem().toString();
            size = "Medium";
            price = 150.00;
        }
        else if(pnmilktea.isSelected() == true && large.isSelected() == true
            && frmilktea.getSelectedIndex()== 2)
        {
            prodcode = "MT124L";
            prodname = "Milktea";
            flavor = frmilktea.getSelectedItem().toString();
            add_ons = addons.getSelectedItem().toString();
            sugar_lvl=sugarlvl.getSelectedItem().toString();
            size = "Large";
            price = 200.00;
        }
        else if(pnmilktea.isSelected() == true && small.isSelected() == true
            && frmilktea.getSelectedIndex()== 3)
        {
            prodcode = "MT125S";
            prodname = "Milktea";
            flavor = frmilktea.getSelectedItem().toString();
            add_ons = addons.getSelectedItem().toString();
            sugar_lvl=sugarlvl.getSelectedItem().toString();
            size = "small";
            price = 100.00;

        }
        else if(pnmilktea.isSelected() == true && medium.isSelected() == true
            && frmilktea.getSelectedIndex()== 3)
        {
            prodcode = "MT125M";
            prodname = "Milktea";
            flavor = frmilktea.getSelectedItem().toString();
            add_ons = addons.getSelectedItem().toString();
            sugar_lvl=sugarlvl.getSelectedItem().toString();
            size = "Medium";
            price = 150.00;
        }
        else if(pnmilktea.isSelected() == true && large.isSelected() == true
            && frmilktea.getSelectedIndex()== 3)
        {
            prodcode = "MT125L";
            prodname = "Milktea";
            flavor = frmilktea.getSelectedItem().toString();
            add_ons = addons.getSelectedItem().toString();
            sugar_lvl=sugarlvl.getSelectedItem().toString();
            size = "Large";
            price = 200.00;
        }
        else if(pnmilktea.isSelected() == true && small.isSelected() == true
            && frmilktea.getSelectedIndex()== 4)
        {
            prodcode = "MT126S";
            prodname = "Milktea";
            flavor = frmilktea.getSelectedItem().toString();
            add_ons = addons.getSelectedItem().toString();
            sugar_lvl=sugarlvl.getSelectedItem().toString();
            size = "small";
            price = 100.00;

        }
        else if(pnmilktea.isSelected() == true && medium.isSelected() == true
            && frmilktea.getSelectedIndex()== 4)
        {
            prodcode = "MT126M";
            prodname = "Milktea";
            flavor = frmilktea.getSelectedItem().toString();
            add_ons = addons.getSelectedItem().toString();
            sugar_lvl=sugarlvl.getSelectedItem().toString();
            size = "Medium";
            price = 150.00;
        }
        else if(pnmilktea.isSelected() == true && large.isSelected() == true
            && frmilktea.getSelectedIndex()== 4)
        {
            prodcode = "MT126L";
            prodname = "Milktea";
            flavor = frmilktea.getSelectedItem().toString();
            add_ons = addons.getSelectedItem().toString();
            sugar_lvl=sugarlvl.getSelectedItem().toString();
            size = "Large";
            price = 200.00;
        }
        else if(pnmilktea.isSelected() == true && small.isSelected() == true
            && frmilktea.getSelectedIndex()== 5)
        {
            prodcode = "MT127S";
            prodname = "Milktea";
            flavor = frmilktea.getSelectedItem().toString();
            add_ons = addons.getSelectedItem().toString();
            sugar_lvl=sugarlvl.getSelectedItem().toString();
            size = "small";
            price = 100.00;

        }
        else if(pnmilktea.isSelected() == true && medium.isSelected() == true
            && frmilktea.getSelectedIndex()== 5)
        {
            prodcode = "MT127M";
            prodname = "Milktea";
            flavor = frmilktea.getSelectedItem().toString();
            add_ons = addons.getSelectedItem().toString();
            sugar_lvl=sugarlvl.getSelectedItem().toString();
            size = "Medium";
            price = 150.00;
        }
        else if(pnmilktea.isSelected() == true && large.isSelected() == true
            && frmilktea.getSelectedIndex()== 5)
        {
            prodcode = "MT127L";
            prodname = "Milktea";
            flavor = frmilktea.getSelectedItem().toString();
            add_ons = addons.getSelectedItem().toString();
            sugar_lvl=sugarlvl.getSelectedItem().toString();
            size = "Large";
            price = 200.00;
        }
        else if(pnfruittea.isSelected() == true && small.isSelected() == true
            && frfruittea.getSelectedIndex()== 1)
        {
            prodcode = "FT310S";
            prodname = "Fruit tea";
            flavor = frfruittea.getSelectedItem().toString();
            add_ons = addons.getSelectedItem().toString();
            sugar_lvl=sugarlvl.getSelectedItem().toString();
            size = "small";
            price = 60.00;
        }
        else if(pnfruittea.isSelected() == true && medium.isSelected() == true
            && frfruittea.getSelectedIndex()== 1)
        {
            prodcode = "FT310M";
            prodname = "Fruit tea";
            flavor = frfruittea.getSelectedItem().toString();
            add_ons = addons.getSelectedItem().toString();
            sugar_lvl=sugarlvl.getSelectedItem().toString();
            size = "Medium";
            price = 80.00;
        }
        else if(pnfruittea.isSelected() == true && large.isSelected() == true
            && frfruittea.getSelectedIndex()== 1)
        {
            prodcode = "FT310L";
            prodname = "Fruit tea";
            flavor = frfruittea.getSelectedItem().toString();
            add_ons = addons.getSelectedItem().toString();
            sugar_lvl=sugarlvl.getSelectedItem().toString();
            size = "Large";
            price = 100.00;
        }
        else if(pnfruittea.isSelected() == true && small.isSelected() == true
            && frfruittea.getSelectedIndex()== 2)
        {
            prodcode = "FT311S";
            prodname = "Fruit tea";
            flavor = frfruittea.getSelectedItem().toString();
            add_ons = addons.getSelectedItem().toString();
            sugar_lvl=sugarlvl.getSelectedItem().toString();
            size = "small";
            price = 60.00;
        }
        else if(pnfruittea.isSelected() == true && medium.isSelected() == true
            && frfruittea.getSelectedIndex()== 2)
        {
            prodcode = "FT311M";
            prodname = "Fruit tea";
            flavor = frfruittea.getSelectedItem().toString();
            add_ons = addons.getSelectedItem().toString();
            sugar_lvl=sugarlvl.getSelectedItem().toString();
            size = "Medium";
            price = 80.00;
        }
        else if(pnfruittea.isSelected() == true && large.isSelected() == true
            && frfruittea.getSelectedIndex()== 2)
        {
            prodcode = "FT311L";
            prodname = "Fruit tea";
            flavor = frfruittea.getSelectedItem().toString();
            add_ons = addons.getSelectedItem().toString();
            sugar_lvl=sugarlvl.getSelectedItem().toString();
            size = "Large";
            price = 100.00;
        }
        else if(pnfruittea.isSelected() == true && small.isSelected() == true
            && frfruittea.getSelectedIndex()== 3)
        {
            prodcode = "FT312S";
            prodname = "Fruit tea";
            flavor = frfruittea.getSelectedItem().toString();
            add_ons = addons.getSelectedItem().toString();
            sugar_lvl=sugarlvl.getSelectedItem().toString();
            size = "small";
            price = 60.00;
        }
        else if(pnfruittea.isSelected() == true && medium.isSelected() == true
            && frfruittea.getSelectedIndex()== 3)
        {
            prodcode = "FT312M";
            prodname = "Fruit tea";
            flavor = frfruittea.getSelectedItem().toString();
            add_ons = addons.getSelectedItem().toString();
            sugar_lvl=sugarlvl.getSelectedItem().toString();
            size = "Medium";
            price = 80.00;
        }
        else if(pnfruittea.isSelected() == true && large.isSelected() == true
            && frfruittea.getSelectedIndex()== 3)
        {
            prodcode = "FT312L";
            prodname = "Fruit tea";
            flavor = frfruittea.getSelectedItem().toString();
            add_ons = addons.getSelectedItem().toString();
            sugar_lvl=sugarlvl.getSelectedItem().toString();
            size = "Large";
            price = 100.00;
        }
        else if(pnfruittea.isSelected() == true && small.isSelected() == true
            && frfruittea.getSelectedIndex()== 4)
        {
            prodcode = "FT313S";
            prodname = "Fruit tea";
            flavor = frfruittea.getSelectedItem().toString();
            add_ons = addons.getSelectedItem().toString();
            sugar_lvl=sugarlvl.getSelectedItem().toString();
            size = "small";
            price = 60.00;
        }
        else if(pnfruittea.isSelected() == true && medium.isSelected() == true
            && frfruittea.getSelectedIndex()== 4)
        {
            prodcode = "FT313M";
            prodname = "Fruit tea";
            flavor = frfruittea.getSelectedItem().toString();
            add_ons = addons.getSelectedItem().toString();
            sugar_lvl=sugarlvl.getSelectedItem().toString();
            size = "Medium";
            price = 80.00;
        }
        else if(pnfruittea.isSelected() == true && large.isSelected() == true
            && frfruittea.getSelectedIndex()== 4)
        {
            prodcode = "FT313L";
            prodname = "Fruit tea";
            flavor = frfruittea.getSelectedItem().toString();
            add_ons = addons.getSelectedItem().toString();
            sugar_lvl=sugarlvl.getSelectedItem().toString();
            size = "Large";
            price = 100.00;
        }
        else if(pnfruittea.isSelected() == true && small.isSelected() == true
            && frfruittea.getSelectedIndex()== 5)
        {
            prodcode = "FT314S";
            prodname = "Fruit tea";
            flavor = frfruittea.getSelectedItem().toString();
            add_ons = addons.getSelectedItem().toString();
            sugar_lvl=sugarlvl.getSelectedItem().toString();
            size = "small";
            price = 60.00;
        }
        else if(pnfruittea.isSelected() == true && medium.isSelected() == true
            && frfruittea.getSelectedIndex()== 5)
        {
            prodcode = "FT314M";
            prodname = "Fruit tea";
            flavor = frfruittea.getSelectedItem().toString();
            add_ons = addons.getSelectedItem().toString();
            sugar_lvl=sugarlvl.getSelectedItem().toString();
            size = "Medium";
            price = 80.00;
        }
        else if(pnfruittea.isSelected() == true && large.isSelected() == true
            && frfruittea.getSelectedIndex()== 5)
        {
            prodcode = "FT314L";
            prodname = "Fruit tea";
            flavor = frfruittea.getSelectedItem().toString();
            add_ons = addons.getSelectedItem().toString();
            sugar_lvl=sugarlvl.getSelectedItem().toString();
            size = "Large";
            price = 100.00;
        }
        else if(pnsmoothie.isSelected() == true && small.isSelected() == true
            && frsmoothie.getSelectedIndex()== 1)
        {
            prodcode = "SM102S";
            prodname = "Smoothie";
            flavor = frsmoothie.getSelectedItem().toString();
            add_ons = addons.getSelectedItem().toString();
            sugar_lvl=sugarlvl.getSelectedItem().toString();
            size = "small";
            price = 80.00;
        }
        else if(pnsmoothie.isSelected() == true && medium.isSelected() == true
            && frsmoothie.getSelectedIndex()== 1)
        {
            prodcode = "SM102M";
            prodname = "Smoothie";
            flavor = frsmoothie.getSelectedItem().toString();
            add_ons = addons.getSelectedItem().toString();
            sugar_lvl=sugarlvl.getSelectedItem().toString();
            size = "Medium";
            price = 120.00;
        }
        else if(pnsmoothie.isSelected() == true && large.isSelected() == true
            && frsmoothie.getSelectedIndex()== 2)
        {
            prodcode = "SM103L";
            prodname = "Smoothie";
            flavor = frsmoothie.getSelectedItem().toString();
            add_ons = addons.getSelectedItem().toString();
            sugar_lvl=sugarlvl.getSelectedItem().toString();
            size = "Large";
            price = 160.00;
        }
        else if(pnsmoothie.isSelected() == true && small.isSelected() == true
            && frsmoothie.getSelectedIndex()== 2)
        {
            prodcode = "SM103S";
            prodname = "Smoothie";
            flavor = frsmoothie.getSelectedItem().toString();
            add_ons = addons.getSelectedItem().toString();
            sugar_lvl=sugarlvl.getSelectedItem().toString();
            size = "small";
            price = 80.00;
        }
        else if(pnsmoothie.isSelected() == true && medium.isSelected() == true
            && frsmoothie.getSelectedIndex()== 2)
        {
            prodcode = "SM103M";
            prodname = "Smoothie";
            flavor = frsmoothie.getSelectedItem().toString();
            add_ons = addons.getSelectedItem().toString();
            sugar_lvl=sugarlvl.getSelectedItem().toString();
            size = "Medium";
            price = 120.00;
        }
        else if(pnsmoothie.isSelected() == true && large.isSelected() == true
            && frsmoothie.getSelectedIndex()== 2)
        {
            prodcode = "SM103L";
            prodname = "Smoothie";
            flavor = frsmoothie.getSelectedItem().toString();
            add_ons = addons.getSelectedItem().toString();
            sugar_lvl=sugarlvl.getSelectedItem().toString();
            size = "Large";
            price = 160.00;
        }
        else if(pnsmoothie.isSelected() == true && small.isSelected() == true
            && frsmoothie.getSelectedIndex()== 3)
        {
            prodcode = "SM104S";
            prodname = "Smoothie";
            flavor = frsmoothie.getSelectedItem().toString();
            add_ons = addons.getSelectedItem().toString();
            sugar_lvl=sugarlvl.getSelectedItem().toString();
            size = "small";
            price = 80.00;
        }
        else if(pnsmoothie.isSelected() == true && medium.isSelected() == true
            && frsmoothie.getSelectedIndex()== 3)
        {
            prodcode = "SM104M";
            prodname = "Smoothie";
            flavor = frsmoothie.getSelectedItem().toString();
            add_ons = addons.getSelectedItem().toString();
            sugar_lvl=sugarlvl.getSelectedItem().toString();
            size = "Medium";
            price = 120.00;
        }
        else if(pnsmoothie.isSelected() == true && large.isSelected() == true
            && frsmoothie.getSelectedIndex()== 3)
        {
            prodcode = "SM104L";
            prodname = "Smoothie";
            flavor = frsmoothie.getSelectedItem().toString();
            add_ons = addons.getSelectedItem().toString();
            sugar_lvl=sugarlvl.getSelectedItem().toString();
            size = "Large";
            price = 160.00;
        }
        else if(pnsmoothie.isSelected() == true && small.isSelected() == true
            && frsmoothie.getSelectedIndex()== 4)
        {
            prodcode = "SM105S";
            prodname = "Smoothie";
            flavor = frsmoothie.getSelectedItem().toString();
            add_ons = addons.getSelectedItem().toString();
            sugar_lvl=sugarlvl.getSelectedItem().toString();
            size = "small";
            price = 80.00;
        }
        else if(pnsmoothie.isSelected() == true && medium.isSelected() == true
            && frsmoothie.getSelectedIndex()== 4)
        {
            prodcode = "SM105M";
            prodname = "Smoothie";
            flavor = frsmoothie.getSelectedItem().toString();
            add_ons = addons.getSelectedItem().toString();
            sugar_lvl=sugarlvl.getSelectedItem().toString();
            size = "Medium";
            price = 120.00;
        }
        else if(pnsmoothie.isSelected() == true && large.isSelected() == true
            && frsmoothie.getSelectedIndex()== 4)
        {
            prodcode = "SM105L";
            prodname = "Smoothie";
            flavor = frsmoothie.getSelectedItem().toString();
            add_ons = addons.getSelectedItem().toString();
            sugar_lvl=sugarlvl.getSelectedItem().toString();
            size = "Large";
            price = 160.00;
        }
        else if(pnsmoothie.isSelected() == true && small.isSelected() == true
            && frsmoothie.getSelectedIndex()== 5)
        {
            prodcode = "SM106S";
            prodname = "Smoothie";
            flavor = frsmoothie.getSelectedItem().toString();
            add_ons = addons.getSelectedItem().toString();
            sugar_lvl=sugarlvl.getSelectedItem().toString();
            size = "small";
            price = 80.00;
        }
        else if(pnsmoothie.isSelected() == true && medium.isSelected() == true
            && frsmoothie.getSelectedIndex()== 5)
        {
            prodcode = "SM106M";
            prodname = "Smoothie";
            flavor = frsmoothie.getSelectedItem().toString();
            add_ons = addons.getSelectedItem().toString();
            sugar_lvl=sugarlvl.getSelectedItem().toString();
            size = "Medium";
            price = 120.00;
        }
        else if(pnsmoothie.isSelected() == true && large.isSelected() == true
            && frsmoothie.getSelectedIndex()== 5)
        {
            prodcode = "SM106L";
            prodname = "Smoothie";
            flavor = frsmoothie.getSelectedItem().toString();
            add_ons = addons.getSelectedItem().toString();
            sugar_lvl=sugarlvl.getSelectedItem().toString();
            size = "Large";
            price = 160.00;
        }

        int qty = Integer.parseInt(txtqty.getValue().toString());
        double tot;
        if (addons.getSelectedIndex()!=0){
            tot = qty * price + 10;
        }
        else
        tot = qty * price;
        model = (DefaultTableModel)tcart.getModel();
        model.addRow(new Object[]
            {
                prodcode,
                prodname,
                flavor,
                size,
                add_ons,
                sugar_lvl,
                price,
                qty,
                tot

            });

            pnmilktea.setSelected(false);
            pnfruittea.setSelected(false);
            pnsmoothie.setSelected(false);
            frmilktea.setSelectedIndex(0);
            frfruittea.setSelectedIndex(0);
            frsmoothie.setSelectedIndex(0);
            small.setSelected(false);
            medium.setSelected(false);
            large.setSelected(false);
            addons.setSelectedIndex(0);
            sugarlvl.setSelectedIndex(0);
            txtqty.setValue(0);

            double sum = 0,sf=50,gamt = 0;
            for(int a=0; a<tcart.getRowCount(); a++)
            {
                sum = sum + Double.parseDouble(tcart.getValueAt(a, 8).toString());

            }
            total.setText(Double.toString(sum));                                
            sfee.setText(Double.toString(sf));
            gamt = sf + sum;
            gamount.setText(Double.toString(gamt));
            

       
        

        

            

    }//GEN-LAST:event_addtocartActionPerformed

    private void largeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_largeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_largeActionPerformed

    private void mediumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mediumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mediumActionPerformed

    private void smallActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smallActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_smallActionPerformed

    private void frsmoothieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_frsmoothieActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_frsmoothieActionPerformed

    private void frfruitteaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_frfruitteaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_frfruitteaActionPerformed

    private void frmilkteaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_frmilkteaActionPerformed
        // TODO add your handling code here:
        //action perform..
        //get selected value from combo box
        String selectedValue =frmilktea.getSelectedItem().toString();
    }//GEN-LAST:event_frmilkteaActionPerformed

    private void pnsmoothieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pnsmoothieActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pnsmoothieActionPerformed

    private void pnfruitteaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pnfruitteaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pnfruitteaActionPerformed

    private void txtcontactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcontactActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcontactActionPerformed

    private void txtaddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtaddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtaddressActionPerformed

    private void txtnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Orderform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Orderform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Orderform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Orderform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Orderform().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> addons;
    private javax.swing.JButton addtocart;
    private javax.swing.JButton backmn;
    private javax.swing.JButton bremove;
    private javax.swing.JTextField custid;
    private javax.swing.JLabel discount;
    private javax.swing.JButton enter;
    private javax.swing.JComboBox<String> frfruittea;
    private javax.swing.JComboBox<String> frmilktea;
    private javax.swing.JComboBox<String> frsmoothie;
    private javax.swing.JLabel gamount;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel87;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JRadioButton large;
    private javax.swing.JLabel ldate;
    private javax.swing.JLabel ltime;
    private javax.swing.JRadioButton medium;
    private javax.swing.JComboBox<String> modep;
    private javax.swing.JTextField orderid;
    private javax.swing.JButton placeorder;
    private javax.swing.JRadioButton pnfruittea;
    private javax.swing.JRadioButton pnmilktea;
    private javax.swing.JRadioButton pnsmoothie;
    private javax.swing.JLabel sfee;
    private javax.swing.JRadioButton small;
    private javax.swing.JComboBox<String> sugarlvl;
    private javax.swing.JTable tcart;
    private javax.swing.JTextField total;
    private javax.swing.JTextField txtaddress;
    private javax.swing.JTextField txtcontact;
    private javax.swing.JTextField txtname;
    private javax.swing.JSpinner txtqty;
    private javax.swing.JTextField vcode;
    // End of variables declaration//GEN-END:variables
}
